from labyrinth_example.labyrinth      import run_labyrinth
from ITER_cylinder.ITER_cyl           import run_ITER_cyl

WW_results_of_labyrinth, no_WW_results_of_labyrinth = run_labyrinth()
WW_results_of_ITER_cyl, no_WW_results_of_ITER_cyl = run_ITER_cyl()

print()
print("-- labyrinth FOM --")
print("with_WW -------------------------------")
print(f"  Avg σ       : {WW_results_of_labyrinth['avg_rel_sigma']:.3e}")
print(f"  Max σ       : {WW_results_of_labyrinth['max_rel_sigma']:.3e}")
print(f"  Transport T.: {WW_results_of_labyrinth['transport_time']:.3f} s")
print(f"  1 / σ²T      : {WW_results_of_labyrinth['figure_of_merit']:.3e}")
print()
print("no_WW -------------------------------")
print(f"  Avg σ       : {no_WW_results_of_labyrinth['avg_rel_sigma']:.3e}")
print(f"  Max σ       : {no_WW_results_of_labyrinth['max_rel_sigma']:.3e}")
print(f"  Transport T.: {no_WW_results_of_labyrinth['transport_time']:.3f} s")
print(f"  1 / σ²T      : {no_WW_results_of_labyrinth['figure_of_merit']:.3e}")

print()
print("-- ITER Cylinder FOM --")
print("with_WW -------------------------------")
print(f"  Avg σ       : {WW_results_of_ITER_cyl['avg_rel_sigma']:.3e}")
print(f"  Max σ       : {WW_results_of_ITER_cyl['max_rel_sigma']:.3e}")
print(f"  Transport T.: {WW_results_of_ITER_cyl['transport_time']:.3f} s")
print(f"  1 / σ²T      : {WW_results_of_ITER_cyl['figure_of_merit']:.3e}")
print()
print("no_WW -------------------------------")
print(f"  Avg σ       : {no_WW_results_of_ITER_cyl['avg_rel_sigma']:.3e}")
print(f"  Max σ       : {no_WW_results_of_ITER_cyl['max_rel_sigma']:.3e}")
print(f"  Transport T.: {no_WW_results_of_ITER_cyl['transport_time']:.3f} s")
print(f"  1 / σ²T      : {no_WW_results_of_ITER_cyl['figure_of_merit']:.3e}")